export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: '1',
      image: '/images/pin.png',
      price: 60,
      product_description: ' Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: '2',
      image: '/images/pin.png',
      price: 50,
      product_description: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Best Pants',
      category: '1',
      image: '/images/pin.png',
      price: 70,
      product_description: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 16,
    }, {
      _id: '4',
      name: 'Best Pants',
      category: '3',
      image: '/images/pin.png',
      price: 70,
      product_description: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Slim Shirt',
      category: '1',
      image: '/images/pin.png',
      price: 60,
      product_description: ' Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Fit Shirt',
      category: '2',
      image: '/images/pin.png',
      price: 50,
      product_description: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '7',
      name: 'Fit Shirt',
      category: '2',
      image: '/images/pin.png',
      price: 50,
      product_description: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '8',
      name: 'Fit Shirt',
      category: '2',
      image: '/images/pin.png',
      price: 50,
      product_description: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
  ]
}